haf/DotNetZip.Semverd

src/Zip/FileSelector.cs, src/Zip/ZipFile.Selector.cs
Improve mono / unix compatibility by removing hardcoded backslashed
paths which prevented ZipFile.SelectEntries to work
Before, it always returned 0 entries because the filenames were not properly parsed.
=> Fix ZipFile.SelectEntries on Unix

src/Zip/ZipEntry.Write.cs
A NullReferenceException was being thrown when a ZipEntry was added with
ZipFile.AddEntry(string, OpenDelegate, CloseDelegate) and ZipFile
attempted a second pass on the input stream. This change forces the
ZipEntry to reopen the stream.
=> Fixed NullReferenceException.

src/Zlib Tests/ZlibUnitTest1.cs
Fix a bug within the parallel deflate test case, where are a reset of the stream's position may lead to a fail of the test.
Fix for https://github.com/haf/DotNetZip.Semverd/issues/48
=> Fix parallel deflate test case

src/Zip Tests/UpdateTests.cs, src/Zip/ZipFile.cs
This fixes #51 by only copying the metadata from the just saved file if the entry in question did not change. Unit test is also included.
=> Fix "Corrupt ZIP file if calling Save twice with UpdateEntry in between #51"

src/Zip Tests/WinZipAesTests.cs, src/Zip/ZipEntry.Extract.cs
Fix for #57 
The stream was disposed too early and therefore the hmac could not be retrieved / checked.
=> AES spanning bug fix

src/Zip/ZipSegmentedStream.cs
This pull request is able to fix an issue found by @somepad
https://github.com/haf/DotNetZip.Semverd/issues/8
=> Set the temp file in the same folder of zip file.

src/Zip/ZipFile.AddUpdate.cs, src/Zip/ZipFile.Read.cs, src/Zip/ZipFile.cs
Alternate fix for #65.
This leaves case-duplicated (multiple entries that differ only in case) alone when reading and writing zip files, and makes `CaseSensitiveRetrieval` only affect searching, as probably originally intended.  Note that enumerating the zip file will still return all entries using their original case, including such duplicates -- but this is also probably as intended.
Mostly, this eliminates an exception that previously occurred when trying to read such files without setting `CaseSensitiveRetrieval` to true prior to reading the file via `Initialize` rather than `Read`.
Minor caveat is that removing entries from zip files will be marginally slower (probably not noticeably so except for zip files with a huge number of entries), but this doesn't seem significant.
Note that …
=> Fix reading of zip files containing entries differing only in case

.semver, src/SolutionInfo.cs, src/Zip Tests/UpdateTests.cs, src/Zip/ZipFile.Save.cs, src/Zip/ZipFile.cs
There was a problem when you executed the following:
1) Open an exisitng ZIP file with at least 2 entries
2) Edit at least one entry **changing it's size**, but **do not touch** at least **one entry after** an edited one
3) Save the ZIP file to a new file, **different than the one which was opened**
4) Save the ZIP file again
What happened at 4) was, that the not changed entry from 2) was read from the initial ZIP file, but with the meta-data from 3) -> the resulting ZIP file of 4) was corrupt as the data read for that entry is shifted.
To fix that when working with files I made sure that the file-name/stream, which is used to read not-edited-entries from, was updated correctly after saving to a new file. As for files only the file-name was used this problem did not occur when saving to …
=> Fix problems when opening ZIP files, editing an entry and saving more than once afterwards

src/Zip/ZipDirEntry.cs, src/Zip/ZipFile.cs
Given zip files that contain duplicate entries, DotNetZip throws an exception after reading a certain number of duplicate entries in the lifetime of the process (and will thereafter be unable to read zips that contain duplicates at all).  Additionally such files are not read the same twice, even if closed and re-read without modifications (since it picks different numbers to rename the duplicates to each time).
This makes two changes to rectify this.
The first is to fix the duplication renaming counter (as discussed in #65) so that the limit is per-entry (as probably intended) instead of per-process.  This ensures consistent renaming and avoids throwing the exception unless a single zip contains excessive duplications of a single entry.
The second adds an option `IgnoreDuplicateFiles` …
=> Ignore duplicates

src/Zlib/ParallelDeflateOutputStream.cs
should resolve #74.
_lastFilled is incremented when work is created
_latestCompressed is set by _DeflateOne
_lastWritten is set by EmitPendingBuffers
All are monotonically incremented.
line 883: if _lastCompressed is equal to _lastFilled then all work is complete, waiting can hang
line 971: if _lastWritten==_lastCompressed, but there is still a worker thread running (ie _lastFilled>_lastCompressed) then the last chunk may not be written by the doAll flush
the change on 971 may slightly change the multi-thread behavior of the proc, if flush(true) is being called from a different thread to write. But in that case the entire current implementation is flaky anyway
=> don't hang if all data already written

src/Zip.Shared/Shared.cs
Was throwing FileNotFoundExceptions with just the filename as the Message - the message should be a readable error message and the filename assigned to the FileName property via the second ctor parameter.
=> Fix FileNotFoundException messages

src/Zip.Shared/ZipEntry.Read.cs
Fix that sizeof ZipEntryDataDescriptorSignature may be added to _LengthOfTrailer more than once in rare case.
=> Fix issue #82

.semver, Gemfile.lock, appveyor.yml, src/SolutionInfo.cs, src/Zip Tests/RandomBytesInputStream.cs, src/Zip Tests/SplitArchives.cs, src/Zip Tests/Zip Tests.csproj, src/Zip Tests/packages.config, src/Zip.Shared/ZipEntry.Write.cs, src/Zip.Shared/ZipFile.Save.cs, src/Zip.Shared/ZipFile.cs, src/Zip.Shared/ZipSegmentedStream.cs
Hello everyone.
I've ran into limitation that max segment size variable is int32, thus the max value is 2gb, which is less than I require. To overcome this issue I've added a 64bit (long) variable alongside the existing one and changed related non-public code to use long instead of int.
I've also added component test to make sure that my changes do not break stuff.
=> Added support for segment sizes over 2gb

src/Zip NetStandard/Zip NetStandard.csproj
Two changes for the .NET Standard project:
1) Include SolutionInfo.cs in the project to pick up the version number (#152)
2) Add AESCRYPTO and BZIP to the defines to match the .NET 4 project
(2) seems to be required to enable AES encryption support in the Standard build.
=> Fixes for the .NET Standard build

.semver, src/SolutionInfo.cs
I'm running into assembly loading errors due to https://github.com/haf/DotNetZip.Semverd/issues/152; the fix is apparently already in master thanks to https://github.com/haf/DotNetZip.Semverd/pull/154, but there's not new version on nuget yet.
Could you push the fixed version to nuget?
=> Bump version so a fixed nuget package can be released

src/Zip Tests/Compatibility.cs, src/Zip Tests/ErrorTests.cs, src/Zip Tests/ExtendedTests.cs, src/Zip Tests/PasswordTests.cs, src/Zip Tests/Streams.cs, src/Zip Tests/Zip64Tests.cs
Looks like some of the unit tests fail because they try to use Ionic.Zip.(dll/pdb) as input to tests and those no longer exist. Change them to use DotNetZip.(dll/pdb) instead
=> Fix some unit tests that were referring to no-longer-created files

src/Zip NetStandard/Zip NetStandard.csproj
The .NET 4.0 version of the assembly is strong named, so perhaps the .NET Standard version should be as well.
=> sign the .NET Standard asembly with Ionic.snk

appveyor.yml
The gem --no-ri option seems to be removed in new gem versions, so try using --no-document instead
=> Change appveyor.yml to use gem install --no-document rather than gem install --no-ri --no-rdoc

src/Zlib.Shared/Inflate.cs, src/Zlib.Shared/ZlibCodec.cs
In order to decode a MSZip file, it requires the ZLib dictionary to be unconditionally set to the previously decoded bytes at the end of each block.
Unfortunately, there is *no* error checking whatsoever involved in this, and it'll quite happily decode garbage data if you do not do this.
This makes it pretty much impossible to implement a sensible working unit test.
Some background and a file in this issue, although this is a MSZip compressed binary X object:
https://github.com/leezer3/OpenBVE/issues/289
I suppose I could hash stream and hash the output if you want?
- This adds an additional method to unconditionally set the dictionary state. MSZip files are uncommon at best, and the error checking is probably useful.
- I was previously using a locally built copy of Ionic.Zlib (1.12.0), …
=> Change: Allow the ZLib dictionary state to be set unconditionally

src/Zip.Shared/ZipFile.cs
Dictionary Lookup is faster: O(1)
This Bug makes Operations really slow when the Number of Files exceeds 25000.
=> fixed O(N²) Performance Bug 

src/Zip/ZipFile.SaveSelfExtractor.cs
We want to be able to create self-extracting archives on systems where .NET 2.0 is not installed. After this change we can specify what version of the csc.exe compiler will be used instead of the hardcoded v2.0. If not specified, the system default one will be used.
=> SFX: Enable CompilerVersion to be specified in SelfExtractorSaveOptions

src/Zip Tests/Selector.cs
On `2020-02-29`, the `DateTime` constructor creating the `threeYearsAgo` variable will attempt to create `2017-02-29`, which doesn't exist since 2017 was not a leap year.  The result is an `ArgumentOutOfRangeException`.
I also fixed a similar occurrence of this pattern in the `twentyYearsAgo` variable construction, though it won't throw since 2000 was indeed a leap year.
See also https://aka.ms/leapday2020blog
=> Repair leap year bugs in unit test

.semver, src/SolutionInfo.cs, src/Zip Tests/Zip64Tests.cs, src/Zip.Shared/ZipEntry.Read.cs
This PR fixes an issue reported in #194 - this was happening a the result of 2 problems:
1. My recent PR #184 with a 'proper' (7-zip and WinZip friendly) way of writing Zip64 header, which have set Disk Start Number in Local & Central entry headers to 0xFFFF and populated the proper value to Zip64, have introduced an incompatibility of DotNetZip-generated zips with DotNetZip itself. 😄
2. Turned out we've never actually supported Disk Start Number in Zip64 header, the comment there stated that we don't support spanning zips, but actually we do
So... I've added the support for Disk Start Number in Zip64 header, it will only be used if it's available (to support more 'exotic' tools than WinZip) and if the Local/Central entry Disk Start Number was 0xFFFF (as prescribed by PKWARE spec).
I've …
=> Added parsing of Disk Start Number from Zip64 header if available

src/Zip.Shared/ZipEntry.cs, src/Zip.Shared/ZipFile.AddUpdate.cs
This is the PR propessed in the https://github.com/haf/DotNetZip.Semverd/issues/209.
Usage is like this:
```
using (var zip1 = ZipFile.Read(stream1))
using (var zip2 = ZipFile.Read(stream2))
{
foreach (var entry in zip2.ToArray())
{
var newEntry = entry.CloneForNewZipFile(zip1);        
newEntry.FileName = $@"zip2/{entry.FileName}";
zipMain.AddEntry(newEntry);
}
zip1.Save(@"C:\temp\merged.zip");
}
```
=> Make it possible to add a ZipEntry from another zip file

.semver, Rakefile, paket.dependencies, paket.lock, src/SolutionInfo.cs
A small hack to replace templates to lower dependencies. Now package dependencies section looks like this:
Compared to current NuGet feed:
=> Switch to lower dependencies
